project:
  type: book

book:
  title: "Life of Python"
  author: "Julio Toboso"
  chapters:
    - index.qmd
    - NumPy.ipynb
    - part: "Data"
      chapters:
        - Pandas.ipynb
    
format:
  html:
    theme: sketchy
    toc: true

execute:
  execute-notebooks: freeze
