project:
  type: book

book:
  title: "Life of Python"
  author: "Julio Toboso"
  chapters:
    - index.qmd
    - part: "Start Here!"
      chapters:
        - wiki/1/What_is_Python.qmd
        - wiki/1/Opening_python.qmd
    - NumPy.ipynb
    - part: "Data"
      chapters:
        - Pandas.ipynb
    - part: "Visual Elements"
      chapters:
        - SVG/SVGGuide.ipynb
     
    
format:
  html:
    theme: simplex
    toc: true

execute:
  execute-notebooks: freeze
